title: Kevin Zhou
author: Kevin
description: High school data scientist exploring ML, AI, statistics

url: "https://kevzho.github.io"
baseurl: ""

permalink: pretty  

sass:
  sass_dir: _sass   # points to your SCSS folder
  style: expanded
  sourcemap: true

theme: null
